---
title: "tree"
output: html_document
---

running

```r
purl("Rscripts/tree.Rmd")
system("nohup R --no-save < tree.R", wait = FALSE)
```
Loading libraries:
```{r}
library(plyr)#try_default
library(rpart)
library(grid)
library(partykit)
library(RWeka)
library(rattle)
library(RColorBrewer)
library(pander)
library(data.table)
library(knitr)
library(printr)

opts_chunk$set(echo = FALSE, message = FALSE, warnings = FALSE,  cache = FALSE)


```


## Data Prep

```{r}
download.file("https://gist.githubusercontent.com/dlebauer/357e02e5f91390fd9ca0/raw/e5f74e0d65b45014ecd9b29d90100b370b1a0f09/yields.csv", method = 'curl', destfile = 'yields.csv')
yields <- fread("yields.csv")

yields$age <- yields$year - yields$planting_date
miscanthus <- yields[genus == "Miscanthus"]

#write.csv(miscanthus, file = "data/miscanthus.csv", row.names = FALSE)
```

```{r data-load}
#miscanthus <- fread("data/miscanthus.csv")

m <- miscanthus[!(is.na(planting_density) | is.na(yield)),
                `:=`(sacchariflorus = grepl('sacchariflorus', species),
                     sinensis = grepl('sinensis', species),
                     sinensis.Hybrid = grepl('Hybrid', species),
                     giganteus = grepl('giganteus', species))]
m<-m[- grep('""""', m$planting_density),]
```

### Climate Data

#### WorldClim

```{r worldclim, eval=FALSE}
library(raster)

x <- getData('worldclim', var='tmin', res=0.5, lon=5, lat=45)

ans <- m[1, list(tmin = getData('worldclim', var = 'tmin', res = 0.5, lon = lon, lat = lat))]
```


#### RNCEP

```{r rncep}
library(maps)
library(RNCEP)
que_xyt <- unique(m[,list(lat, lon, year)])

get_met <- function(year, lat, lon, var){
  ans <- NULL
  ans <- try_default(quiet = TRUE, default = NA, expr = 
                       NCEP.gather(variable = var, level='gaussian', months.minmax=c(5,9), years.minmax = c(year,year), lat.southnorth = c(lat,lat), lon.westeast=c(lon,lon), reanalysis2 = TRUE, return.units = FALSE, status.bar=FALSE)
                     )
  
  if(any(!is.na(ans))){
    lats <- as.numeric(dimnames(ans)[[1]])
    lons <- as.numeric(dimnames(ans)[[2]])
    lons[lons>180] <- lons[lons>180] - 360
    dlat <- abs(lat - lats)
    dlon <- abs(lon - lons)
    #weights
    wlat <- dlat/sum(dlat, na.rm = TRUE)
    wlon <- dlon/sum(dlon, na.rm = TRUE)
    
    weights <- as.matrix(wlat) %*% t(as.matrix(wlon))
    
    
    ans2 <- rowMeans(ans, dims = 2, na.rm = TRUE)
    ans2.1 <- ans2[!is.nan(ans2)]
    
    ans3 <- sum(ans2.1 * weights)
    }
  return(ans3)
  }

## MAT = Mean Annual Temperature
ncep_data_list <- list()
for(i in 1:nrow(unique_xyt)){
  ncep_data_list[[i]] <- que_xyt[i, list(lat, lon, year, MAT = mean(get_met(year, lat, lon, 'air.2m')),
                                      MAP = sum(get_met(year, lat, lon, 'prate.sfc')),
                                      PET = mean(get_met(year, lat, lon, 'pevpr.sfc')),
                                      SOLAR = sum(get_met(year, lat, lon, 'dswrf.sfc'))
                                      )]
  
  
  ncep_data <- rbindlist(ncep_data_list)
  save(ncep_data, file = "~/ncep_data.RData") 
  }


ggplot() + geom_point(data = ncep_data, aes(lon, lat, color = MAP/PET))
```

```{r joindata}
m$SOLAR=0
m$MAP=0
m$MAT=0
m$PET=0


m$giganteus <- NULL
m$sinensis.Hybrid <- NULL
m$sinensis <- NULL
m$sacchariflorus <-NULL

m$giganteus = 0
m$sinensis.Hybrid = 0 
m$sinensis = 0
m$sacchariflorus = 0
m$irrigation = 0

for(i in 1:nrow(m)){
  
  if(m[i]$species == "Miscanthus x giganteus")
      m[i]$giganteus = 1
  else if (m[i]$species == "Miscanthus sacchariflorus")
      m[i]$sacchariflorus = 1
  else if (m[i]$species == "Miscanthus sinensis Hybrid")
      m[i]$sinensis.Hybrid = 1
  else if (m[i]$species == "Miscanthus sinensis")
      m[i]$sinensis = 1
  
  if(m[i]$irrigated == "TRUE")
      m[i]$irrigation <- 1

  
  for(j in 1:nrow(ncep_data)){
      if (m[i]$lat == ncep_data[j]$lat 
          && m[i]$lon == ncep_data[j]$lon 
          && m[i]$year == ncep_data[j]$year){
        m[i]$MAT <- ncep_data[j]$MAT
        m[i]$MAP <- ncep_data[j]$MAP
        m[i]$PET <- ncep_data[j]$PET
        m[i]$SOLAR <- ncep_data[j]$SOLAR
      }
      next
  }
  print(i)
}
m$planting_density = as.numeric(as.character(m$planting_density))

```

#### Daymet

_note:_ daymet only covers US, Canada, Mexico

```{r daymet, eval=FALSE}
if(require(DaymetR)){
  install_bitbucket("khufkens/daymetr", subdir = 'DaymetR')
} 
library(DaymetR)

dm <- list()
new_xyt <- unique_xyt[lon < -30]
for(i in 1:nrow(new_xyt)){
  rm(Daymet)
  try(
    new_xyt[i, download.daymet(lat = lat, lon = lon,internal = FALSE,  start_yr = year, end_yr = year)]
    )
  
  if(exists("Daymet")){
    d <- data.table(Daymet$data)

    dm[[i]] <- d[yday > 90 & yday < 270,
                 list(lat = Daymet$lattitude,
                      lon = Daymet$longitude,
                      elev = Daymet$altitude,
                      year = unique(year),
                      temp = mean(c(tmax..deg.c., 
                                    tmin..deg.c.)),
                      precip = sum(prcp..mm.day.),
                      vpd = mean(vp..Pa.))]
    } else {
      dm[[i]] <- NA
    }
  save(dm, file = "data/daymet.RData")
}

```
## Analyses


### Regression Tree

```{r reg-tree}
treedata <- m
treedata$lat <- NULL
treedata$lon <- NULL
treedata$newMAP <- 100000*treedata$MAP

treedata$P_PET <- treedata$MAP * 100000 / treedata$PET
rtree <- rpart(yield ~ age + P_PET + newMAP + PET +
                 MAT + SOLAR + 
                 sacchariflorus + sinensis + sinensis.Hybrid + giganteus +
                 fertilizer_n + irrigation + planting_density , 
               data = treedata,
               maxdepth = 6,
              # minbucket = 15,
               xval = 2,
               method="anova")

plot(as.party(rtree),tp_args=list(id=FALSE))
plot(rtree)
pander(rtree$cptable)

cp9 = which(rtree$cptable[, 2] == 6)
rtree = prune(rtree, rtree$cptable[cp9, 1])

opt <- which.min(rtree$cptable[,"xerror"])
cp <- rtree$cptable[opt,"CP"]

rtree_prune <- prune(rtree,cp=cp)
plot(as.party(rtree_prune),tp_args=list(id=FALSE))
plot(rtree_prune)
summary(rtree)
```

TODO what do you see? what does it mean?

## Using M5P algorithm

```{r M5P}

m2 <- m[,list(yield, sacchariflorus = as.numeric(sacchariflorus), 
              sinensis = as.integer(sinensis), 
              sinensis.Hybrid = as.integer(sinensis.Hybrid), 
              giganteus = as.integer(giganteus),
              irrigated = as.integer(irrigated),
              lat, lon, fertilizer_n,  planting_density)]
m2[] <- lapply(m2, as.numeric)

m5pTree <- M5P(yield ~ sacchariflorus + sinensis + sinensis.Hybrid + giganteus +
                 lat + lon + fertilizer_n + irrigated + planting_density, 
         data = m2)


summary(m5pTree)
plot(m5pTree)
```

TODO what do you see? what does it mean?